"$schema" = "https://starship.rs/config-schema.json"

[kotlin]
disabled = false

[java]
disabled = true

[gradle]
disabled = true

[python]
disabled = true

[nodejs]
disabled = true

[aws]
disabled = false

[lua]
disabled = false

[package]
disabled = true

[golang]
disabled = true

[rust]
disabled = true

[hostname]
ssh_symbol = ""

[helm]
disabled = true

[time]
disabled = true
time_format = "%T"
utc_time_offset = "0"
format = '[$time UTC]($style) '


[cmd_duration]
disabled = true
min_time = 60000
